added more logging and better install for mac apps

diff --git a/run_once/run_once_install_apps.sh.tmpl b/run_once/run_once_install_apps.sh.tmpl
--- a/run_once/run_once_install_apps.sh.tmpl
+++ b/run_once/run_once_install_apps.sh.tmpl
@@ -10,6 +10,29 @@ log_message() {
     echo "[$current_time] $message" | tee -a "$LOG_FILE"
 }
 
+# function to enable logging of commands that run
+run_command() {
+    local command="$*"
+    log_message "Executing: $command"
+    
+    # Execute the command using eval
+    output=$(eval "$command" 2>&1)
+    exit_code=$?
+
+    # Log the command output
+    log_message "Output: $output"
+
+    # Log success or failure based on the exit code
+    if [ $exit_code -eq 0 ]; then
+        log_message "Command succeeded."
+    else
+        log_message "Command failed with exit code $exit_code."
+    fi
+
+    # Return the exit code to allow for error handling
+    return $exit_code
+}
+
 # INSTALL: any tool that can be deployed via a package manager across all distro's and have a new enough version
 INSTALL=( bat curl gh git jq mosh pandoc pass ripgrep tmux btop podman wget zsh )
 
@@ -25,10 +48,10 @@ log_message "########################################################"
 
 {{- if eq .chezmoi.osRelease.id "debian" }}
 
-sudo apt update && sudo apt upgrade -y  
+run_command sudo apt update && sudo apt upgrade -y  
 
-echo ${INSTALL[@]} | xargs sudo apt install -y 
-echo ${DEBIAN[@]} | xargs sudo apt install -y 
+run_command echo ${INSTALL[@]} | xargs sudo apt install -y 
+run_command echo ${DEBIAN[@]} | xargs sudo apt install -y 
 
 {{- end}}
 
@@ -40,75 +63,75 @@ log_message "########################################################"
 if ! command -v nvim &> /dev/null
 then
   log_message "building nvim"
-  git clone --depth=1 https://github.com/neovim/neovim
-  cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
-  git checkout stable
-  sudo make install
+  run_command git clone --depth=1 https://github.com/neovim/neovim
+  run_command cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
+  run_command git checkout stable
+  run_command sudo make install
 fi
 
 # install ohmyposh
 if ! command -v oh-my-posh &> /dev/null
 then
   log_message "installing ohmyposh"
-  curl -s https://ohmyposh.dev/install.sh | bash -s
+  run_command curl -s https://ohmyposh.dev/install.sh | bash -s
 fi
 
 # install fzf
 if ! command -v fzf &> /dev/null
 then
   log_message "installing fzf"
-  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
-  ~/.fzf/install --no-update-rc
+  run_command git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
+  run_command ~/.fzf/install --no-update-rc
 fi
 
 # install zoxide
 if ! command -v zoxide &> /dev/null
 then
   log_message "installing zoxide"
-  curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
+  run_command curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
 fi
 
 # install cargo and rust
 if ! command -v cargo &> /dev/null
 then
   log_message "installing cargo"
-  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
-  source $HOME/.cargo/env
+  run_command curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
+  run_command source $HOME/.cargo/env
 fi
 
 # install go
 if ! command -v go &> /dev/null
 then
   log_message "installing go"
-  curl -LO https://get.golang.org/$(uname)/go_installer && \
+  run_command curl -LO https://get.golang.org/$(uname)/go_installer && \
   chmod +x go_installer && \
   ./go_installer && \
-  rm go_installer
-  export PATH=$PATH:/usr/local/go/bin
+  run_command rm go_installer
+  run_command export PATH=$PATH:/usr/local/go/bin
 fi
 
 # install eza
 if ! command -v eza &> /dev/null
 then
   log_message "installing eza"
-  $HOME/.cargo/bin/cargo install eza 
+  run_command $HOME/.cargo/bin/cargo install eza 
 fi
 
 # install rargs
 if ! command -v rargs &> /dev/null
 then
   log_message "installing rargs"
-  $HOME/.cargo/bin/cargo install --git https://github.com/lotabout/rargs.git
+  run_command $HOME/.cargo/bin/cargo install --git https://github.com/lotabout/rargs.git
 fi
 
 # install TPM for TMUX
-[ ! -d $HOME/.tmux/plugins ] && log_message "installing tpm" && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
+run_command [ ! -d $HOME/.tmux/plugins ] && log_message "installing tpm" && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
 
 # install cheat
 if ! command -v cheat &> /dev/null
 then
   log_message "Installing cheat"
-  go install github.com/cheat/cheat/cmd/cheat@latest
+  run_command go install github.com/cheat/cheat/cmd/cheat@latest
 fi
 
 {{- if eq .chezmoi.osRelease.id "darwin" }}
@@ -122,26 +145,39 @@ log_message "  "
 
 if ! command -v brew &> /dev/null
 then
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+  log_message "installing Homebrew"
+  run_command /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 fi
 
-defaults write -g NSWindowShouldDragOnGesture -bool true
-
-brew update
+run_command defaults write -g NSWindowShouldDragOnGesture -bool true
+run_command defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
+run_command brew update
 
 # Install aerospace window manager
-brew install --cask nikitabobko/tap/aerospace
+if ! command -v aerospace &> /dev/null
+then
+  log_message "Installing aerospace"
+  run_command brew install --cask nikitabobko/tap/aerospace
+fi
 
 # install jankybar for the green window highlights
-brew tap FelixKratz/formulae
-brew install borders
+if ! command -v borders &> /dev/null
+then
+  log_message "Installing Borders"
+  run_command brew tap FelixKratz/formulae
+  run_command brew install borders
+fi
 
-brew tap FelixKratz/formulae
-brew install sketchybar
-brew services start sketchybar
+if ! command -v sketchybar &> /dev/null
+then
+  run_command brew tap FelixKratz/formulae
+  run_command brew install sketchybar
+  # brew services start sketchybar
+fi
 
-echo ${INSTALL[@]} | xargs brew install  
-echo ${BREW[@]} | xargs brew install  
+log_message "Installing some apps"
+run_command echo ${INSTALL[@]} | xargs brew install  
+run_command echo ${BREW[@]} | xargs brew install  
 
 {{- end }}
 
@@ -155,8 +191,8 @@ log_message "  "
 log_message "checking if nvim is the default editor"
 if [[ ! $(update-alternatives --query editor | grep 'Value:' | awk '{print $2}') == *nvim* ]]; then
   log_message "setting nvim to default editor"
-  sudo update-alternatives --install /usr/bin/editor editor $(which nvim) 60
-  sudo update-alternatives --config editor
+  run_command sudo update-alternatives --install /usr/bin/editor editor $(which nvim) 60
+  run_command sudo update-alternatives --config editor
 else
   log_message "nvim is default editor"
 fi
